import sqlmodel

"""edit tableee

Revision ID: 167ab72e608d
Revises: bed9fa819f5d
Create Date: 2025-03-29 16:15:56.099439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167ab72e608d'
down_revision: Union[str, None] = 'bed9fa819f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
