import sqlmodel

"""add doctor status

Revision ID: 31f0fc547ca3
Revises: e20e698d08a4
Create Date: 2025-04-07 13:59:07.281129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31f0fc547ca3"
down_revision: Union[str, None] = "e20e698d08a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable first
    op.add_column(
        "doctor",
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )

    # Step 2: Set default status for existing records
    op.execute("UPDATE doctor SET status = 'inactive'")

    # Step 3: Alter the column to be non-nullable
    op.alter_column("doctor", "status", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctor", "status")
    # ### end Alembic commands ###
