import sqlmodel

"""modified appointment status 2

Revision ID: 47d69b743f20
Revises: e20e698d08a4
Create Date: 2025-04-06 18:32:38.154354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d69b743f20'
down_revision: Union[str, None] = 'e20e698d08a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
