import sqlmodel

"""message3343

Revision ID: 4965c6cfb62a
Revises: d8f0ea0b1858
Create Date: 2025-04-03 15:49:32.144028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4965c6cfb62a'
down_revision: Union[str, None] = 'd8f0ea0b1858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
