import sqlmodel

"""add_ehr_status_enum

Revision ID: 521623d90454
Revises: 47d69b743f20
Create Date: 2025-04-06 18:41:47.439027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521623d90454'
down_revision: Union[str, None] = '47d69b743f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ehr', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('INITIATED', 'VITALS_RECORDED', 'DIAGNOSED', 'COMPLETED', name='ehrstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ehr', 'status',
               existing_type=sa.Enum('INITIATED', 'VITALS_RECORDED', 'DIAGNOSED', 'COMPLETED', name='ehrstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
