import sqlmodel

"""message33435

Revision ID: b4b799c2ba6c
Revises: 4965c6cfb62a
Create Date: 2025-04-03 16:30:02.305338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b799c2ba6c'
down_revision: Union[str, None] = '4965c6cfb62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
