import sqlmodel

"""edit tablee

Revision ID: bed9fa819f5d
Revises: e47d364d446d
Create Date: 2025-03-28 22:44:46.812907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed9fa819f5d'
down_revision: Union[str, None] = 'e47d364d446d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
