import sqlmodel

"""edit table

Revision ID: e47d364d446d
Revises: b62d230748bc
Create Date: 2025-03-26 01:28:07.202402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47d364d446d'
down_revision: Union[str, None] = 'b62d230748bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'specialization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
